language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true

branches:
  only:
    - master

notifications:
  email:true

env:
  global:
  - GH_REF=https://github.com/Starrier/Dreamwar.git
