server:
  port: 8080
spring:
  application:
    name: service-article

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&&useSSL=false
    username: Starrier
    password: starrier&1103
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 20
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: select 1
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 2000
      stat-view-servlet:
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        url-pattern: /druid/*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 5
    jedis:
      pool:
       min-idle: 0
       max-idle: 10
       max-wait: 1
       max-active: 8
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    host: localhost
    port: 5672
    publisher-confirms: true
  mail:
    host: smtp.qq.com
    username: 1342878298@qq.com
    password: kguvdnnqvintfjff
    default-encoding: UTF-8
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.starrier.dreamwar.model


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql